### ISSUE TITLE
ScrollTrigger for column is buggy

### ISSUE THREAD

**Issue by NicholasLYang** [EmoryDHLab/data-by-design#11]
This might be an implementation issue on my part but when I use the `ScrollTrigger` feature on `Column` in Peabody, it seems [a little buggy](https://www.loom.com/share/3facc501060e488592a0320a84b34ea2)

**Comment by jayvarner** [comment]
Good catch. It looks like the behavior improves if you add vertical padding to the `TwoCloumnLayout` component, eg `py-10`. It also improves if you remove the scrollytell placeholder. I can take a closer look when I'm back in the office.

**Comment by jayvarner** [comment]
@NicholasLYang, the commit referenced above is a potential fix. I say "potential" because I could not consistently replicate the behavior you found. Anyway, the change is in how the end trigger is calculated.

**Comment by jayvarner** [comment]
Should be resolved by #14
